### ISSUE TITLE
[McM] load McM from /afs/cern.ch/cms/PPD/PdmV/tools/McM/

### ISSUE THREAD

**Issue by gkrintir** [cms-PdmV/mcm_scripts#4]
Hi @justinasr @pgunnell

I have a quick question.

Have you encountered any issues loading McM from:

/afs/cern.ch/cms/PPD/PdmV/tools/McM/ ?

Since last week I cannot retrieve requests when passing any given prepid, e.g, using this [script](https://github.com/cms-sw/genproductions/blob/master/test/calculateXSectionAndFilterEfficiency/compute_cross_section.py#L57).

Regards and many thanks im advance!

**Comment by pgunnell** [comment]
Hi Georgios,
mmm actually not..can you try now?

**Comment by gkrintir** [comment]
Thanks a lot Paolo!

Indeed, it works now.

Did you actually have to perform any adjustment or it was simply me? 

Regards
