### ISSUE TITLE
Include support for ID tokens

### ISSUE THREAD

**Issue by ggonzr** [cms-PdmV/mcm_scripts#8]
## Feature request: Include support for ID tokens

Related to the SSO migration, include support for ID tokens to allow users to authenticate and perform actions to McM by including these JWT before using this client or requesting them on their behalf before performing any operation.

### Is your feature related to a problem?

Colleagues who have enabled a second-factor authentication will not be able to use the current SDK client and request credentials via `auth-get-sso-cookie` package. Requesting session cookies having enabled 2FA is not supported by the [package](https://auth.docs.cern.ch/applications/command-line-tools/). It is required to bring support to the new authentication schema to allow them to continue using this SDK.

### Describe the solution you'd like

To keep backward compatibility, the SDK should attempt to request a session cookie by using the available package. If the package is not available, other authentication schemes should be explored like requesting an ID token via `auth-get-user-token` package (if available) or by performing a [device code authorization grant](https://auth.docs.cern.ch/user-documentation/oidc/device-code/). 

If a session cookie or an ID token is given by the caller/user of the SDK. The SDK must verify if these credentials are valid before performing the desired action (GET a resource, PUT a change, etc.).

## Current behavior

A session cookie is requested/given to authenticate the user’s actions. 

## Expected behavior

McM SDK requests/uses authentication credentials and provides other authentication schemes based on the following rules:

* [x] If a session cookie is given, McM SDK checks if it is valid to perform further operations. One way to achieve this is by performing an HTTP request to the home page and checking the response code, if this credential is invalid an HTTP 302 will be received.

* [x] If an ID token is given, McM SDK checks if it is valid before starting any authentication flow. If it is not valid, it should follow authentication flows to request a valid credential.

* [x] If there is no session cookie given, McM SDK will try to request a new session cookie if the package `auth-get-sso-cookie` is available in the user/caller runtime environment. If the package is not available, another authentication schema must be used. If the package is available and the session cookie request finishes successfully, it must be verified before using it to perform an action.

* [x] ~~If package `auth-get-user-token` is not available in the user/caller runtime environment, McM SDK must perform a device authorization grant, to achieve this, the required code must be included in the SDK source code. Also, this should handle properly the interactive actions of the user.~~. If it is required to request an ID token, execute the `Device Authorization Grant` via HTTP requests

### Constraints

* [x] All HTTP requests have to be handled only by using Python core packages. The use of [`requests`](https://pypi.org/project/requests/) library is forbidden. We don’t want to force our users to handle virtual environments and external packages.

### To be aware of / to discuss in comments

* [x] If the user provides a JWT, make sure it is an ID token and not an access token, we should raise a warning alerting them. To check if the given JWT is an ID token, we can perform a request to a resource. If it is an access token an error could be raised from the backend because access tokens are not related to users returning this 403 or 401 HTTP response code.

**Comment by lmoureaux** [comment]
> All HTTP [requests](https://pypi.org/project/requests/) have to be handled only by using Python core packages. The use of requests library is forbidden. We don’t want to force our users to handle virtual environments and external packages.

We can provide a virtual environment for our deployment on lxplus, other uses are supported on a best-effort basis.

**Comment by ggonzr** [comment]
I think we can complete that constraint with not much effort. The only case that is not currently available by the [__http_request(..)](https://github.com/cms-PdmV/mcm_scripts/blob/enhancement/id-tokens/rest.py#L99) method is for performing url-encoded requests. This kind of request can be achieved by encoding parameters using urllib.parse() and changing the 'Content-Type' like the following [example](https://github.com/cms-PdmV/Stats2/blob/SSOMigration/utils.py#L148). Also, we should change that method to allow invoking request for other hosts

**Comment by ggonzr** [comment]
Also, we can not drop the support for Python 2. McM still uses this SDK for some integration scripts: [1](https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/automatic_scripts/GrimReaper.py#L6), [2](https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/automatic_scripts/bump_miniaod_priority.py#L7)

**Comment by lmoureaux** [comment]
> Also, we can not drop the support for Python 2. McM still uses this SDK for some integration scripts: [1](https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/automatic_scripts/GrimReaper.py#L6), [2](https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/automatic_scripts/bump_miniaod_priority.py#L7)

Nice find :+1: I think it would be cleaner to have a copy of the (old unsupported) Python 2 code somewhere within the McM deployment instead of relying on afs. This change can be largely transparent.

**Comment by lmoureaux** [comment]
`auth-get-user-token` isn't supported for our use case:

> The scope of this tool is to have an easy way for debugging/testing authentication for APIs and web applications from the command line. It can also work for securing APIs as an alternative to cern-get-sso-cookie, but **it is not supported for production services.**

(emphasis mine)

**Comment by lmoureaux** [comment]
> All HTTP [requests](https://pypi.org/project/requests/) have to be handled only by using Python core packages. The use of requests library is forbidden. We don’t want to force our users to handle virtual environments and external packages.

Note that `auth-get-sso-cookie`, `auth-get-sso-token`, and `auth-get-user-token` already use `requests` :D It's installed for both Python 2 and 3 on lxplus.

**Comment by lmoureaux** [comment]
`auth-get-user-token` performs a device authorization grant. So we can ~code it ourselves~ *copy it from there* and just do that, no need to implement two methods of doing the same.

**Comment by lmoureaux** [comment]
I'm following the flow from [this section](https://gitlab.cern.ch/authzsvc/tools/auth-get-sso-cookie#auth-get-user-token) of the official docs:
* Get an access token with `auth-get-sso-cookie`
* Send an HTTP request with that token as a bearer

Unfortunately this doesn't work and I'm presented with the login page. Refreshing the token does work as expected so I suspect an issue with our middleware. I think it might be an issue that needs solving in the middleware.

My work so far can be found here: https://github.com/cms-PdmV/mcm_scripts/pull/9

**Comment by lmoureaux** [comment]
Device authorization flows using the `cms-ppd-pdmv` client ID with `auth-get-user-token` fails:
```
ERROR: Authentication request failed: Device authorization response was not successful. Response:
{"error":"unauthorized_client","error_description":"Invalid client or Invalid client credentials"}
```
